# Generated by Django 4.2.23 on 2025-07-18 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactmessage',
            name='sent_at',
        ),
    ]
