# Generated by Django 4.2.23 on 2025-07-21 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_message_delete_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
